server:
  port: 8080
spring:
  application:
    name: user
  datasource:
    url: jdbc:postgresql://postgres:5432/user
    username: postgres
    password: postgres
    driver: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        hbm2ddl.auto: update
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  level:
    org:
      springframework: DEBUG
      hibernate: DEBUG
