spring:
  application:
    name: user
  datasource:
    url: jdbc:postgresql://localhost:5432/user
    username: postgres
    password: postgres
    driver: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        hbm2ddl.auto: update
#        cache:
#          caches:
#            -name: booksCache
#          use_second_level_cache: true
#          region:
#            factory_class: com.hazelcast.hibernate.HazelcastCacheRegionFactory
#liquibase:
#  change-log: classpath:/db/changelog/db.changelog-master.yaml
#  contexts: development, production
#  default-schema: book
logging:
  level:
#    org.springframework.data.mongodb.core: debug
    hibernate: debug








